spring:
    kafka:
        bootstrap-servers: kafka:9092
    cloud:
        stream:
            bindings:
                nounsupplier-out-0:
                    destination: nounrequest
                nounconsumer-in-0:
                    destination: nounresponse
                verbsupplier-out-0:
                    destination: verbrequest
                verbconsumer-in-0:
                    destination: verbresponse
                adverbsupplier-out-0:
                    destination: adverbrequest
                adverbconsumer-in-0:
                    destination: adverbresponse
        function:
            definition: nounconsumer;verbconsumer;adverbconsumer
